apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: frontend
  namespace: five31
spec:
  endpointSelector:
    matchLabels:
      app: frontend

  ingress:
    # Allow ingress from Tailscale
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: tailscale
            tailscale.com/parent-resource: frontend
            tailscale.com/parent-resource-ns: five31
      toPorts:
        - ports:
            - port: '3000'
              protocol: TCP

  egress:
    # Allow egress to kube-dns (needed for DNS resolution)
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: '53'
              protocol: TCP
            - port: '53'
              protocol: UDP

    # Allow egress to backend
    - toEndpoints:
        - matchLabels:
            app: backend
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP

    # Allow egress to world for Google SSO
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: '443'
              protocol: TCP
