name: ktlint

on:
  pull_request:
    branches: [master]

jobs:
  ktlint:
    name: 'ktlint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run ktlint checks
        working-directory: backend
        run: |
          ./gradlew loadKtlintReporters
          # For *.kts files
          ./gradlew runKtlintCheckOverKotlinScripts
          ./gradlew ktlintKotlinScriptCheck
          # For *.kt files in /src/main
          ./gradlew runKtlintCheckOverMainSourceSet
          ./gradlew ktlintMainSourceSetCheck
